server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # Permite mapear rutas usando los nombres de Eureka
      routes:
        # 1. AUTH-SERVICE
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**

        # 2. USUARIO-SERVICE
        - id: usuario-service
          uri: lb://usuario-service
          predicates:
            - Path=/api/v1/usuarios/**

        # 3. PROPIEDAD-SERVICE
        - id: propiedad-service
          uri: lb://propiedad-service
          predicates:
            - Path=/api/v1/propiedades/**

        # 4. RESERVA-SERVICE
        - id: reserva-service
          uri: lb://reserva-service
          predicates:
            - Path=/api/v1/reservas/**

        # 5. BUSQUEDA-SERVICE
        - id: busqueda-service
          uri: lb://busqueda-service
          predicates:
            - Path=/api/v1/busqueda/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Esto te ayudará a ver en la consola cómo se redirigen las peticiones automáticamente
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG