server.port=8080
spring.application.name=api-gateway

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# JWT
jwt.secret=unaClaveSecretaMuyLargaParaQueSeaSegura123456

# Logs
logging.level.org.springframework.cloud.gateway=DEBUG