
server.port=8080
spring.application.name=api-gateway

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
jwt.secret=unaClaveSecretaMuyLargaParaQueSeaSegura123456
# Rutas hacia cada microservicio
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://auth-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/auth/**

spring.cloud.gateway.routes[1].id=usuario-service
spring.cloud.gateway.routes[1].uri=lb://usuario-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/usuarios/**

spring.cloud.gateway.routes[2].id=propiedad-service
spring.cloud.gateway.routes[2].uri=lb://propiedad-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/propiedades/**

spring.cloud.gateway.routes[3].id=reserva-service
spring.cloud.gateway.routes[3].uri=lb://reserva-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/v1/reservas/**

spring.cloud.gateway.routes[4].id=resena-service
spring.cloud.gateway.routes[4].uri=lb://resena-service
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/v1/resenas/**

spring.cloud.gateway.routes[5].id=busqueda-service
spring.cloud.gateway.routes[5].uri=lb://busqueda-service
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/v1/busqueda/**

spring.cloud.gateway.routes[6].id=notificacion-service
spring.cloud.gateway.routes[6].uri=lb://notificacion-service
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/v1/notificaciones/**

spring.cloud.gateway.routes[7].id=imagen-service
spring.cloud.gateway.routes[7].uri=lb://imagen-service
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/v1/imagenes/**

spring.cloud.gateway.routes[8].id=reporte-service
spring.cloud.gateway.routes[8].uri=lb://reporte-service
spring.cloud.gateway.routes[8].predicates[0]=Path=/api/v1/reportes/**

# Logs para ver que rutas se activan
logging.level.org.springframework.cloud.gateway=DEBUG