server:
  port: 8080

spring:
  application:
    name: api-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: 123456

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.mvc: TRACE
    org.springframework.web.servlet: DEBUG